### ISSUE TITLE
WARN - Failed to load the `eslint` library for 'file.js'

### ISSUE THREAD

**Issue by Ruakij** [manuth/VSCodeESLintLanguageService#122]
Hi.

Whenever i have the extension active, i get this warning in the problems-tab:

```
files.js:
  Failed to load the `eslint` library for 'file.js'
  To use `eslint` please install the `eslint`-module using 'npm install eslint' orusing 'npm install -g eslint' to install it globally.
  Be sure to restart your editor after the installation. eslint(1) [1, 1]
```
_`file.js` is the current active file._

<br>

eslint is installed using `npm install -g eslint`

eslint itself works fine, thats why i was so confused when i saw this warning.

<br>

```
eslint --version
> v8.4.1
```

```
which eslint
> /usr/bin/eslint
```

**Comment by neurolag** [comment]
Hello @Ruakij
Sadly, I had to notice, that `eslint` isn't suited for the use as a typescript language service anymore.

Language services are bound to be written synchronously by typescript. However - the new version of `eslint` (from version 8 forward) only provide asynchronous methods.

This means, I'll have to wait until either of it changes (i.e. until typescript language services may specify asynchronous `getSemanticDiagnostics` implementations or until `eslint` decides to add synchronous methods back again).

Until then I will have to put this project on hold.

Feel free to use @Quramy's `typescript-eslint-language-service` until then (which only works on linux and macOS at time of writing) or Microsoft's recommended `ESLint` extension: https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

These two options use `eslint`s private API and might suit your need.

Sorry for having to disappoint you

**Comment by Ruakij** [comment]
Ah, okay, didnt knew things changed.

Thank you for the names/links.
I am on linux, so thats perfect.
