### ISSUE TITLE
Could You please change the icon/description in the VSCode marketplace?

### ISSUE THREAD

**Issue by yungParrot** [manuth/VSCodeESLintLanguageService#148]
I tried to install ESLint in VSCode and by mistake I've downloaded Your plugin instead of the
[official ESLint plugin](https://github.com/Microsoft/vscode-eslint) and I couldn't figure out why linting didn't work in my project...  
I've figured out that Your extension, looks nearly the same as the official eslint extension for some reason 🙄

**Comment by neurolag** [comment]
Sorry for the inconvenience - I'll go unpublish my extension.
Doesn't look like TypeScript language server's or ESLint's public API will change anytime soon anyways.
